name: Build and Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    # branches:
    # branches-ignore:
    #  - master
    #  - alpha

jobs:
  build-test:
    name: Build, Lint and Test
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@269a893f6432649083afd1c3c6350793e8c00e4b
